### ISSUE TITLE
Error in macOS 15.0 Sequoia Beta 

### ISSUE THREAD

**Issue by starv** [orchetect/SettingsAccess#12]
![Xnapper-2024-06-12-11 59 04](https://github.com/orchetect/SettingsAccess/assets/1267399/ba799f24-4f41-4b75-91b3-964c7baf5f83)
Fyi, on the first beta of Sequoia, SettingsAccess errors out, saying `Ambiguous use of 'openSettings`.

**Comment by orchetect** [comment]
Thanks for the heads-up.

The beta just came out in the last couple days so I haven't had a chance to spin it up yet. This isn't surprising, as I suspect Apple has been further changing things under the hood with the new OS release (and may continue to do so until public release). I'll try to get a compatibility update pushed soon.

**Comment by orchetect** [comment]
I just ran some tests and it seems like now that Apple is exposing its `openSettings` environment method publicly, the best course for SettingsAccess is to rename its `openSettings` to `openSettingsLegacy`.

It will allow the same SettingsAccess behavior when calling it to continue functioning as before, where apps need to support OS versions older than macOS 14 (since Apple's `openSettings` is unavailable prior to macOS 14). But it won't conflict with the namespace for the new environment method if people choose to use it.

**Comment by orchetect** [comment]
Pushed release 2.0.0 that adds support for Xcode 16.

**Comment by starv** [comment]
Works like a charm! 👌❤️
